from ultralytics import YOLO

model_base = YOLO("dlt-models/yolo11n.yaml")
model_s_base = YOLO("dlt-models/yolo11s.yaml")
model_8n = YOLO("yolov8n.yaml")
model_bic_repc3k2 = YOLO("dlt-models/yolo11n-bic-repc3k2.yaml")
model_bic_repc3k2_fa = YOLO("dlt-models/yolo11n-bic-repc3k2-fa.yaml")
model_bic_repc3k2_eca = YOLO("dlt-models/yolo11n-bic-repc3k2-eca.yaml")
model_bic_repc3k2_simam = YOLO("dlt-models/yolo11n-bic-repc3k2-simam.yaml")
model_bic_repc3k2_se = YOLO("dlt-models/yolo11n-bic-repc3k2-se.yaml")
model_bic_repc3k2_hconv = YOLO("dlt-models/yolo11n-bic-repc3k2-hconv.yaml")
model_bic_repc3k2_cl = YOLO("dlt-models/yolo11n-bic-repc3k2-cl.yaml")
model_bic_repc3k2_ca = YOLO("dlt-models/yolo11n-bic-repc3k2-ca.yaml")
model_bic_carepc3k2 = YOLO("dlt-models/yolo11n-bic-carepc3k2.yaml")
model_bic_repc3k2_gc = YOLO("dlt-models/yolo11n-bic-repc3k2-gc.yaml")
model_bic_repc3k2_gc_spdconv = YOLO("dlt-models/yolo11n-bic-repc3k2-gc-spdconv.yaml")
model_bic_repc3k2_sppfcsp = YOLO("dlt-models/yolo11n-bic-repc3k2-sppfcsp.yaml")
model_bic_repc3k2_simsppfcsp = YOLO("dlt-models/yolo11n-bic-repc3k2-simsppfcsp.yaml")
model_bic_repc3k2_simsppf = YOLO("dlt-models/yolo11n-bic-repc3k2-simsppf.yaml")
model_bic_rfac3k2 = YOLO("dlt-models/yolo11n-bic-rfac3k2.yaml")
model_spdconv1_bic_repc3k2 = YOLO("dlt-models/yolo11n-spdconv1-bic-repc3k2.yaml")

model_bic_repc3k2_sppfcsp = YOLO("dlt-models/yolo11n-bic-repc3k2-sppfcsp.yaml")
model_bic_repc3k2_simsppfcsp = YOLO("dlt-models/yolo11n-bic-repc3k2-simsppfcsp.yaml")


model_base = YOLO("dlt-models/yolo11n.yaml")
model_s_base = YOLO("dlt-models/yolo11s.yaml")
model_8n = YOLO("yolov8n.yaml")

model_base.info()
model_s_base.info()
model_8n.info()


# model_base.info()
# model_s_base.info()
# model_8n.info()
# model_bic_repc3k2.info()
# model_bic_repc3k2_fa.info()
# model_bic_repc3k2_eca.info()
# model_bic_repc3k2_simam.info()
# model_bic_repc3k2_se.info()
# model_bic_repc3k2_hconv.info()
# model_bic_repc3k2_cl.info()
# model_bic_repc3k2_ca.info()
# model_bic_carepc3k2.info()
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-repc3k2-gc.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-repc3k2-gc-spdconv.yaml")
# model_bic_repc3k2_sppfcsp.info()
# model_bic_repc3k2_simsppfcsp.info()
# model_bic_repc3k2_simsppf.info()

# model_ghostconv = YOLO("dlt-models/yolo11n-GhostConv.yaml")
# model_spdconv = YOLO("dlt-models/yolo11n-SPDConv.yaml")
# model_repconv = YOLO("dlt-models/yolo11n-RepConv.yaml")
# model_rfaconv = YOLO("dlt-models/yolo11n-RFAConv.yaml")
# model_fem = YOLO("dlt-models/yolo11n-FEM.yaml")
# model_fa = YOLO("dlt-models/yolo11n-FA.yaml")
# model_bifpn1 = YOLO("dlt-models/yolo11n-BiFPN-1.yaml")
# model_bifpn2 = YOLO("dlt-models/yolo11n-BiFPN-2.yaml")
# model_bifpn3 = YOLO("dlt-models/yolo11n-BiFPN-3.yaml")
# model_bifpn4 = YOLO("dlt-models/yolo11n-BiFPN-4.yaml")
# model_bifpn5 = YOLO("dlt-models/yolo11n-BiFPN-5.yaml")
# model_bifpn6 = YOLO("dlt-models/yolo11n-BiFPN-6.yaml")
# model_cl = YOLO("dlt-models/yolo11n-CL.yaml")
# model_simsppf = YOLO("dlt-models/yolo11n-SimSPPF.yaml")
# model_se = YOLO("dlt-models/yolo11n-SE.yaml")
# model_eca = YOLO("dlt-models/yolo11n-ECA.yaml")
# model_simam = YOLO("dlt-models/yolo11n-SimAM.yaml")
# model_se_skip = YOLO("dlt-models/yolo11n-SE-skip.yaml")
# model_eca_skip = YOLO("dlt-models/yolo11n-ECA-skip.yaml")
# model_simam_skip = YOLO("dlt-models/yolo11n-SimAM-skip.yaml")
# model_fem2 = YOLO("dlt-models/yolo11n-FEM2.yaml")
# model = YOLO("dlt-models/yolo11n.yaml")
# model_efficientspdconv = YOLO("dlt-models/yolo11n-EfficientSPDConv.yaml")
# model_efficientspdconv2 = YOLO("dlt-models/yolo11n-EfficientSPDConv2.yaml")
# model_sppffem = YOLO("dlt-models/yolo11n-SPPFFEM.yaml")
# model_efficientfem = YOLO("dlt-models/yolo11n-EfficientFEM.yaml")
# model_spdconv2 = YOLO("dlt-models/yolo11n-SPDConv-2.yaml")
# # model_spdconv3 = YOLO("dlt-models/yolo11n-SPDConv-3.yaml")
# model_dwspdconv = YOLO("dlt-models/yolo11n-DWSPDConv.yaml")
# model_hconv = YOLO("dlt-models/yolo11n-HConv.yaml")
# model_ghostspdconv = YOLO("dlt-models/yolo11n-GhostSPDConv.yaml")
# model_progressive_spdconv = YOLO("dlt-models/yolo11n-ProgSPDConv.yaml")
# model_repc3k2 = YOLO("dlt-models/yolo11n-RepC3k2.yaml")
# model_rfac3k2 = YOLO("dlt-models/yolo11n-RFAC3k2.yaml")
# model_yolo11s = YOLO("yolo11s.yaml")
# model_spdconv_gc = YOLO("dlt-models/yolo11n-spdconv-gc.yaml")
# model_spdconv_sppfcsp = YOLO("dlt-models/yolo11n-spdconv-sppfcsp.yaml")
# model_biformer = YOLO("dlt-models/yolo11n-biformer.yaml")
# # model_biformer_noc2psa = YOLO("dlt-models/yolo11n-biformer-noc2psa.yaml")
# # model_biformer_selective_1 = YOLO("dlt-models/yolo11n-biformer-selective-1.yaml")
# # model_biformer_selective_2 = YOLO("dlt-models/yolo11n-biformer-selective-2.yaml")


# model_ghostconv.info()
# model_spdconv.info()
# model_repconv.info()
# model_rfaconv.info()
# model_fem.info()
# model_fa.info()
# model_bifpn1.info()
# model_bifpn2.info()
# model_bifpn3.info()
# model_bifpn4.info()
# model_bifpn5.info()
# model_bifpn6.info()
# model_cl.info()
# model_simsppf.info()
# model_se.info()
# model_eca.info()
# model_simam.info()
# model_se_skip.info()
# model_eca_skip.info()
# model_simam_skip.info()
# model_fem2.info()
# model.info()
# model_efficientspdconv.info()
# model_efficientspdconv2.info()
# model_sppffem.info()
# model_efficientfem.info()
# model_spdconv2.info()
# model_dwspdconv.info()
# model_hconv.info()
# model_ghostspdconv.info()
# model_progressive_spdconv.info()
# model_repc3k2.info()
# model_rfac3k2.info()
# model_yolo11s.info()
# model_spdconv_gc.info()
# model_spdconv_sppfcsp.info()
# profile_model_with_dummy_conv("dlt-models/yolo11n-SPDConv-3.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-full.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-reduced-channel.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-reduced-channel-simple-upsample.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-selective-1.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-selective-2.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-transpose.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-concat.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-spdconv-4.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-reduced-channel-sppfcsp.yaml")
# model_biformer.info()
# # model_biformer_noc2psa.info()
# # model_biformer_selective_1.info()
# # model_biformer_selective_2.info()
# # profile_model_with_dummy_conv("dlt-models/yolo11n-bic-reduced-channel-bottleneckbiformer.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-reduced-channel-simam.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-afr-reduced-channel.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-reduced-channel-gsconv.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-reduced-channel-enhancedc3k2.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-reduced-channel-rfac3k2.yaml")
# profile_model_with_dummy_conv("dlt-models/yolo11n-bic-reduced-channel-repc3k2.yaml")
